Feature comments
vnnazaren/ewm pull request #3
Opened 2024-06-15 14:28 UTC by vnnazaren

2024-06-16 18:27 UTC, z8q requested changes

2024-06-16 18:27 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +    public CommentDto createComment(Long userId, Long eventId, CommentDto commentDto) {
Над публичными методами, которые мы переопределяем у интерфейса нужно еще поставить аннотацию '@Override'

2024-06-16 18:27 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +        Optional<Comment> foundComment = commentRepository.findByEventIdAndAuthorId(eventId, userId);
можно использовать orElseThrow после вызова findByEventIdAndAuthorId вместо блока if в 54-й строке

2024-06-16 18:27 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +        Optional<Comment> comment = commentRepository.findById(commentId);
тут тоже можно применить orElseThrow, это позволит не использовать конструкцию if-else

2024-06-16 20:57 UTC, vnnazaren commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +        Optional<Comment> foundComment = commentRepository.findByEventIdAndAuthorId(eventId, userId);
Да  я вообще сознательно так сделал, так как там делаю несколько проверок подряд, прежде чем можно будет сохранить коммент пользователя. С if'ами выглядит однообразно и понятно. Но раз такое требование - поменял.

2024-06-16 21:34 UTC, vnnazaren commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +        Optional<Comment> foundComment = commentRepository.findByEventIdAndAuthorId(eventId, userId);
Ещё немного подумал и в общем orElseThrow тут не поможет.
Вернул обратно, только малёхо оптимизировал: переменную там не обязательно объявлять, так как она не используется.
А саму конструкцию вернул, так как там надо проверить - есть ли значение в переменной Optional и если есть - бросить исключение.

2024-06-16 22:23 UTC, vnnazaren commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +    public CommentDto createComment(Long userId, Long eventId, CommentDto commentDto) {
Готово.

2024-06-16 22:24 UTC, vnnazaren commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CommentServiceImpl.java
> +        Optional<Comment> comment = commentRepository.findById(commentId);
Готово.

2024-06-17 15:52 UTC, z8q approved these changes

2024-06-18 07:53 UTC, merged